/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCourseCourseIdIndexRouteImport } from './routes/_authenticated/course.$courseId/index'
import { Route as AuthenticatedCourseCourseIdFolderIdRouteImport } from './routes/_authenticated/course.$courseId/$folderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCourseCourseIdIndexRoute =
  AuthenticatedCourseCourseIdIndexRouteImport.update({
    id: '/course/$courseId/',
    path: '/course/$courseId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCourseCourseIdFolderIdRoute =
  AuthenticatedCourseCourseIdFolderIdRouteImport.update({
    id: '/course/$courseId/$folderId',
    path: '/course/$courseId/$folderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/course/$courseId/$folderId': typeof AuthenticatedCourseCourseIdFolderIdRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/course/$courseId/$folderId': typeof AuthenticatedCourseCourseIdFolderIdRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/course/$courseId/$folderId': typeof AuthenticatedCourseCourseIdFolderIdRoute
  '/_authenticated/course/$courseId/': typeof AuthenticatedCourseCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/course/$courseId/$folderId'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/course/$courseId/$folderId' | '/course/$courseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/course/$courseId/$folderId'
    | '/_authenticated/course/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/course/$courseId/': {
      id: '/_authenticated/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AuthenticatedCourseCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/course/$courseId/$folderId': {
      id: '/_authenticated/course/$courseId/$folderId'
      path: '/course/$courseId/$folderId'
      fullPath: '/course/$courseId/$folderId'
      preLoaderRoute: typeof AuthenticatedCourseCourseIdFolderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCourseCourseIdFolderIdRoute: typeof AuthenticatedCourseCourseIdFolderIdRoute
  AuthenticatedCourseCourseIdIndexRoute: typeof AuthenticatedCourseCourseIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCourseCourseIdFolderIdRoute:
    AuthenticatedCourseCourseIdFolderIdRoute,
  AuthenticatedCourseCourseIdIndexRoute: AuthenticatedCourseCourseIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
